[colors.primary]
background = "#282c34"
foreground = "#d7dae0"
dim_foreground = "#42464e"
bright_foreground = "#6f737b"

[colors.cursor]
text = "#d7dae0"
cursor = "#6f737b"

[colors.vi_mode_cursor]
text = "#d7dae0"
cursor = "#6f737b"

[colors.search.matches]
foreground = "#1e222a"
background = "#6f737b"

[colors.search.focused_match]
foreground = "#1e222a"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e222a"
background = "#6f737b"

[colors.hints.start]
foreground = "#1e222a"
background = "#6f737b"

[colors.hints.end]
foreground = "#1e222a"
background = "#6f737b"

[colors.selection]
text = "#d7dae0"
background = "#42464e"

[colors.normal]
black = "#1e222a"
red = "#e06c75"
green = "#98c379"
yellow = "#e7c787"
blue = "#61afef"
magenta = "#f2a8d5"
cyan = "#42b3c2"
white = "#d7dae0"

[colors.bright]
black = "#565c64"
red = "#be5046"
green = "#7eca9c"
yellow = "#d19a66"
blue = "#4dc4ff"
magenta = "#ec76bd"
cyan = "#4cd1e0"
white = "#e6e6e6"
