#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar               all:34:0       \
                mouse_follows_focus        on            \
                focus_follows_mouse        autoraise      \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             off            \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.8            \
                window_animation_duration  0.5            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                4              \
                bottom_padding             4              \
                left_padding               4              \
                right_padding              4              \
                window_gap                 6

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add app="^Cisco Secure Client$" manage=off

yabai -m config layout bsp

# Sketchybar: Report window update events
yabai -m signal --add event=window_title_changed action="sketchybar --trigger yabai_front_window_updated WINDOW_ID=\$YABAI_WINDOW_ID" active=yes
yabai -m signal --add event=window_focused action="sketchybar --trigger yabai_front_window_updated WINDOW_ID=\$YABAI_WINDOW_ID"
yabai -m signal --add event=space_changed action="sketchybar --trigger yabai_front_window_updated WINDOW_ID=\$(yabai -m query --windows --space \$YABAI_SPACE_INDEX | jq -c '.[] | select( .\"has-focus\"==true ).id')"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger yabai_front_window_updated WINDOW_ID=\$(yabai -m query --windows | jq -c '.[] | select( .\"has-focus\"==true ).id')"

echo "yabai configuration loaded.."
